### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by lumag**
Resources allocated by XkbGetMap() should be freed by XkbFreeKeyboard.
Otherwise I get the following leaked memory report from Valgrind:

==14972== 1,920 bytes in 48 blocks are definitely lost in loss record 1,598 of 1,626
==14972==    at 0x402C118: calloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==14972==    by 0x5064EA8: XkbGetMap (in /usr/lib/i386-linux-gnu/libX11.so.6.3.0)
==14972==    by 0x428019D: grab_ungrab (bind.c:203)
==14972==    by 0x4280320: do_grab_key (bind.c:326)
==14972==    by 0x4280721: keybinder_bind_full (bind.c:574)
==14972==    by 0x4280791: keybinder_bind (bind.c:539)
==14972==    by 0x8049220: xvd_keys_init (xvd_keys.c:141)
==14972==    by 0x8048F84: main (main.c:126)

### CODE REVIEW

**Comment by engla** [comment]
Thank you! Commits merged, including adapting to the keybinder-3.0 branch (which really is the primary branch nowadays).

New releases for version 0.3.1 tagged for both packages.

I don't have a website, so nowhere to put the release tarballs. They can be generated from the source

```
./autogen.sh --prefix=/usr --enable-gtk-doc --enable-introspection=yes && make && make dist
```

If a new maintainer would step up, it's very welcome.

**Comment by lumag** [comment]
@engla you can use GitHub release system to publish tarballs.

**Comment by engla** [comment]
Those are just source snapshots, not `make dist` tarballs.

**Comment by lumag** [comment]
Not quite true... For example check https://github.com/lumag/emv-tools/releases/tag/v0.1
There is an "upload binary" button.

**Comment by engla** [comment]
Nice. I suppose github has improved since 2012 :smile:

**Comment by engla** [comment]
New Releases

- [keybinder v0.3.1](https://github.com/engla/keybinder/releases/tag/v0.3.1)
- [keybinder-3.0 v0.3.1](https://github.com/engla/keybinder/releases/tag/keybinder-3.0-v0.3.1)

**Pull request merged**
